#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

./Allrun.pre

# Initialise with potentialFoam solution
#runApplication potentialFoam -pName p -writephi

# Parallel
runApplication decomposePar
mpirun -hostfile hostfile -np 20 overPimpleDyMFoam -parallel > log.overPimpleDyMFoam

# Run it for a bit
#runApplication $(getApplication)
./makeFiles
#./prepareForceDat
#------------------------------------------------------------------------------
